apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base configuration
resources:
- ../base

# Remove load generator
components:
- ../components/without-loadgenerator

# Reduce resources for 2 services
patchesStrategicMerge:
- reduce-resources.yaml
