apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
spec:
  type: ClusterIP
  selector:
    app: recommendationservice
    # PAS de version ici ! Le service envoie vers v1 ET v2
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
